FROM node:20.11.1-bullseye AS server-builder
RUN apt update && apt install -y git git-lfs p7zip-full && \
    GIT_LFS_SKIP_SMUDGE=1 git clone -b 4.0.x-DEV --depth=1 https://github.com/AirryCo/spt-server.git /snapshot && \
    cd /snapshot && git config -f .lfsconfig lfs.url https://git.rui.he.cn:3000/henry/spt-server.git/info/lfs && git lfs pull && \
    cd project && \
    npm install && npm run build:release && \
    rm -rf /var/lib/apt/lists/*

FROM debian:bookworm-slim
LABEL author="AirryCo <henry@stblog.com.cn>"
ENV TZ=Asia/Shanghai
COPY --from=server-builder /snapshot/project/build/ /app/spt-server/
VOLUME /opt/spt-server
WORKDIR /opt/spt-server
EXPOSE 6969
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

